# Generated by Django 2.1.7 on 2019-02-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('message', '0006_delete_usermessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('object_id', models.CharField(default='', max_length=50, primary_key=True, serialize=False, verbose_name='主键')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='用户名')),
                ('time', models.EmailField(max_length=254, verbose_name='提交时间')),
                ('address', models.CharField(max_length=50, verbose_name='联系地址')),
                ('message', models.CharField(max_length=100, verbose_name='提交信息')),
            ],
            options={
                'verbose_name_plural': '用户提交信息',
                'db_table': 'user_message',
                'ordering': ('-object_id',),
            },
        ),
    ]
